### ISSUE TITLE
Cannot pull cfme docker image

### ISSUE THREAD

**Issue by ffirg** [redhatdemocentral/rhcs-cloudforms-demo#1]
+ docker pull ecwpz91/cfme4-demo
Using default tag: latest
Error response from daemon: repository ecwpz91/cfme4-demo not found: does not exist or no pull access

**Comment by ffirg** [comment]
It's gone : https://hub.docker.com/r/ecwpz91/cfme4-demo/ = 404

**Comment by eschabell** [comment]
Yes, aware this has been taken offline, so working on getting this moved so that we can generate a container installation after downloading the product.

**Comment by eschabell** [comment]
Just letting you know, we are working on this right now.... It has not slipped. Stay tuned.

**Comment by 1robroos** [comment]
Dear eschabell, do you have an update ?
Rob

**Comment by eschabell** [comment]
Not yet, it's on my todo list, but low priority right now... stay tuned.

**Comment by radus2k** [comment]
I knew someone will remind you about this old project. 

BTW congrats for Summit presentation I was trying to ask you about this during the Summit but no luck. You where to busy every time I saw you:(

**Comment by eschabell** [comment]
@radus2k , sorry it was busy time for me... I will get to this soon.

**Comment by nitram88** [comment]
Dear eschabell, do you have any updates on this?
Thanks in advance
Martin

**Comment by eschabell** [comment]
@nitram88, not yet, it is about providing the product externally... still working on this but taking much longer than expected. I will post when it's live again.

**Comment by eschabell** [comment]
Just an update, still working on this.... had an container image on OCP 3.6 but it was not functioning and eventually failed, working on persistence. Slow going.

**Comment by eschabell** [comment]
Finished up the fixes needed to offer CloudForms 4.5 containerized on OpenShift Container Platform v3.6, released as version 1.1. https://github.com/redhatdemocentral/rhcs-cloudforms-demo/commit/93b06bc7da533b153a6924d82450c3540c0c1571
