### ISSUE TITLE
line 120 won't work with minishift 1.5.0?

### ISSUE THREAD

**Issue by ffirg** [redhatdemocentral/rhcs-cloudforms-demo#3]
you hard code system:admin into line 120:
oc login $HOST_IP:8443 -u system:admin

system doesn't have the same privs under minishift?

**Comment by eschabell** [comment]
These demos target OpenShift Container Platform and not the community OpenShift Origin. You definitely will have to find ways to get the proper access and not sure the oc client you are using will work. 

I have no plans to support this.
