### ISSUE TITLE
Is there any support for running this ontop of minishift that's running on Windows

### ISSUE THREAD

**Issue by LW81** [redhatdemocentral/rhcs-cloudforms-demo#4]
Hi,

i have setup a minishift based OpenShift environment on my Windows 10 Laptop using VirtualBox.
Is there anything available that would let me deploy that demo ontop of this ?

Thx

**Comment by eschabell** [comment]
I have not tried pushing to mini-shift, but it is possible to point the init.sh at any open shift installation, just open and update the login / password / host name variables found at the top to point to your specific installation (shown here from init.sh):

# Adjust these variables to point to an OCP instance.
OPENSHIFT_USER=admin
OPENSHIFT_PWD=admin
HOST_IP=yourhost.com

PS. I don't have an init.bat yet, but if you can take one of the other demos found here and use the init.bat as a template, test and give me a PR, I would be really grateful. The other option is to ask nicely if @sabre1041 would pull one together for us as he is able to test that?

**Comment by eschabell** [comment]
@LW81 just pushed a new (untested) init.bat file, can you try it out and validate if it works?

**Comment by sabre1041** [comment]
@eschabell I will also give it a spin this evening

**Comment by eschabell** [comment]
This fix by @sabre1041 has been tested, so closing issue as provides windows installer.
