### ISSUE TITLE
does not work in cases where console is not on 8443

### ISSUE THREAD

**Issue by tomazb** [redhatdemocentral/rhcs-cloudforms-demo#6]
Hello!

Port 8443 is hard-coded into the init.sh. It should be configurable thing. 

Also when you are remote this will not work:
oc login $HOST_IP:8443 -u system:admin

**Comment by eschabell** [comment]
This project moved to Gitlab in June 2018:

https://gitlab.com/redhatdemocentral/rhcs-cloudforms-demo

Can you please reopen here: 

https://gitlab.com/redhatdemocentral/rhcs-cloudforms-demo/issues/new
