### ISSUE TITLE
CF_IMAGE_TEMPLATE needs to be updated

### ISSUE THREAD

**Issue by tomazb** [redhatdemocentral/rhcs-cloudforms-demo#7]
I had to change the init.sh in order to get the CF template.

The old one:
CF_IMAGE_TEMPLATE="https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_examples/files/examples/v3.6/cfme-templates/cfme-template.yaml"

The working one from the master:
CF_IMAGE_TEMPLATE="https://raw.githubusercontent.com/openshift/openshift-ansible/master/roles/openshift_management/files/templates/cloudforms/cfme-template.yaml"

_

**Comment by eschabell** [comment]
This project moved to Gitlab in June 2018:

https://gitlab.com/redhatdemocentral/rhcs-cloudforms-demo

I've opened this one to be fixed by me here so you can track it:

https://gitlab.com/redhatdemocentral/rhcs-cloudforms-demo/issues/6
